Repository FACG5/PBI, pull requests merged in 2018-10, with the labels that each got.

#29 database schema
  package-lock.json
  package.json
  src/app.js
  src/database/dbConnect.js
  src/database/models/admin.js
  src/database/models/certificate.js
  src/database/models/employee.js
  src/database/models/fixedVarible.js
  src/database/models/purchaseBox.js
  src/database/models/purchasesEmployee.js
  src/database/models/report.js
  src/index.js
Labels: awaiting-review

#39 convert camel-case to snake-case
  src/middleware/convertCamelToSnake.js
Labels: awaiting-review, urgent

#37 General settings
  public/css/generalSettings.css
  src/controllers/generalSettings.js
  src/controllers/index.js
  src/controllers/setting.js
  src/database/models/fixedVarible.js
  src/views/generalSettings.hbs
  src/views/setting.hbs
Labels: awaiting-review

#44 improving adding new Employee
  package.json
  public/css/swal.css
  public/js/addEmployee.js
  src/app.js
  src/controllers/addEmployee.js
  src/controllers/cart.js
  src/controllers/employees.js
  src/controllers/generalSettings.js
  src/controllers/overview.js
  src/views/addEmployee.hbs
  src/views/employees.hbs
  src/views/layouts/main.hbs
  src/views/partials/head.hbs
Labels: awaiting-review, urgent

#53 fixing error in editing general Setting #51
  public/js/generalSetting.js
  src/controllers/generalSettings.js
  src/views/generalSettings.hbs
Labels: awaiting-review

#54 Login
  package-lock.json
  package.json
  public/css/login.css
  public/js/login.js
  src/controllers/index.js
  src/controllers/login.js
  src/views/layouts/login.hbs
  src/views/login.hbs
Labels: awaiting-review

#56 make the logout #55
  public/js/logout.js
  src/controllers/index.js
  src/controllers/logout.js
  src/views/layouts/main.hbs
  src/views/partials/head.hbs
  src/views/partials/sidebar.hbs
Labels: awaiting-review

#57 Employee details
  public/css/employeeDetails.css
  public/js/employeeDetails.js
  src/controllers/employeeDetails.js
  src/controllers/helper/convertSnakeToCamel.js
  src/controllers/index.js
  src/views/employeeDetails.hbs
  src/views/layouts/main.hbs
  src/views/partials/head.hbs
Labels: awaiting-review

#61 fixing error page router #30
  src/controllers/index.js
Labels: awaiting-review

#66 employee page
  src/views/employeeDetails.hbs
Labels: bug

#64 Edit cart
  public/css/cart.css
  public/js/cart.js
  src/controllers/cart.js
  src/controllers/index.js
  src/views/cart.hbs
Labels: awaiting-review

#79 edit the maxAge to 30 minutes
  src/controllers/login.js
Labels: awaiting-review

#81 Add link to employees
  public/css/tables.css
  src/controllers/employees.js
  src/views/employees.hbs
Labels: awaiting-review

#76 Authentication
  src/controllers/generalSettings.js
  src/controllers/index.js
  src/middleware/loginAuthenticate.js
Labels: awaiting-review

#74 add the active class #72
  public/css/public.css
  src/controllers/cart.js
  src/controllers/employees.js
  src/controllers/generalSettings.js
  src/controllers/overview.js
  src/controllers/reports.js
  src/controllers/setting.js
  src/views/partials/sidebar.hbs
Labels: awaiting-review

#71 uploading certificates when adding employee
  package.json
  public/css/employees.css
  public/js/addEmployee.js
  public/js/setting.js
  src/app.js
  src/controllers/addEmployee.js
  src/controllers/files.js
  src/controllers/index.js
  src/controllers/reports.js
  src/database/query/bonusQuery.js
  src/database/query/deductionsQuery.js
  src/database/query/exemptions.js
  src/views/addEmployee.hbs
  src/views/employeeDetails.hbs
Labels: awaiting-review

#83 General editions
  package.json
  public/css/public.css
  public/js/generalSetting.js
  src/controllers/addEmployee.js
  src/controllers/employeeDetails.js
  src/controllers/generalSettings.js
  src/controllers/index.js
  src/views/layouts/main.hbs
  src/views/partials/sidebar.hbs
Labels: awaiting-review

#97 Excel enhancement
  src/controllers/helpers/excelSheets/columns.js
  src/controllers/helpers/excelSheets/dataSet.js
  src/controllers/helpers/excelSheets/excelSheetMain.js
  src/controllers/helpers/salaryMain.js
  src/controllers/reports.js
Labels: awaiting-review

#102 Update purchase boxex for each employee
  public/css/employeeDetails.css
  public/js/employeeDetails.js
  src/controllers/editEmployee.js
  src/controllers/employeeDetails.js
  src/database/query/purchaseEmployees.js
  src/database/query/updatePurchase.js
  src/views/employeeDetails.hbs
Labels: awaiting-review

#105 Employee report
  public/css/employeeDetails.css
  public/css/employeeReport.css
  public/js/employeeReport.js
  src/controllers/employeeDetails.js
  src/controllers/employeeReport.js
  src/controllers/index.js
  src/database/models/report.js
  src/views/employeeDetails.hbs
  src/views/employeeReport.hbs
  src/views/layouts/employeeReport.hbs
  src/views/layouts/main.hbs
  src/views/partials/employeeReportHead.hbs
Labels: awaiting-review

#108 fixing error in hbs files
  src/views/addEmployee.hbs
  src/views/employeeReport.hbs
Labels: urgent
